import json
import os

with open('schema_dump.json', 'r') as f:
    schema = json.load(f)

# 1. Generate Oracle SQL Schema
sql_lines = []
sql_lines.append("-- Technopath Oracle SQL Schema")
sql_lines.append("-- Generated automatically")
sql_lines.append("")

# Maps Django internal types to Oracle SQL types
TYPE_MAPPING = {
    'AutoField': 'NUMBER GENERATED BY DEFAULT AS IDENTITY',
    'BigAutoField': 'NUMBER GENERATED BY DEFAULT AS IDENTITY',
    'CharField': 'VARCHAR2',
    'TextField': 'CLOB',
    'IntegerField': 'NUMBER(10)',
    'BigIntegerField': 'NUMBER(19)',
    'SmallIntegerField': 'NUMBER(5)',
    'PositiveIntegerField': 'NUMBER(10)',
    'PositiveSmallIntegerField': 'NUMBER(5)',
    'FloatField': 'FLOAT',
    'DecimalField': 'NUMBER',
    'BooleanField': 'NUMBER(1)',
    'NullBooleanField': 'NUMBER(1)',
    'DateTimeField': 'TIMESTAMP',
    'DateField': 'DATE',
    'TimeField': 'TIMESTAMP',
    'FileField': 'VARCHAR2(255)',
    'ImageField': 'VARCHAR2(255)',
    'EmailField': 'VARCHAR2',
    'URLField': 'VARCHAR2',
    'UUIDField': 'VARCHAR2(36)',
    'ForeignKey': 'NUMBER',
    'OneToOneField': 'NUMBER',
    'Field': 'VARCHAR2(255)' # fallback
}

deferred_fks = []

for table_name, data in schema.items():
    if not table_name:
        continue
    
    sql_lines.append(f"CREATE TABLE {table_name} (")
    fields_sql = []
    
    for field in data['fields']:
        if field['name'] is None:
            continue
        col_name = field['name']
        django_type = field['type']
        
        # Determine base type
        sql_type = TYPE_MAPPING.get(django_type, 'VARCHAR2(255)')
        
        if django_type in ['CharField', 'EmailField', 'URLField'] and field.get('max_length'):
            sql_type = f"VARCHAR2({field['max_length']})"
            
        # Primary Key
        if field['pk']:
            if sql_type == 'NUMBER':
                sql_type = 'NUMBER GENERATED BY DEFAULT AS IDENTITY'
            sql_type += " PRIMARY KEY"
            
        # Nullability
        if not field['null'] and not field['pk'] and "IDENTITY" not in sql_type:
            sql_type += " NOT NULL"
            
        fields_sql.append(f"    {col_name} {sql_type}")
        
        # Foreign Key
        if field['fk'] and field['fk_table']:
            deferred_fks.append(f"ALTER TABLE {table_name} ADD CONSTRAINT {table_name}_{col_name}_fk FOREIGN KEY ({col_name}) REFERENCES {field['fk_table']}(id);")

    sql_lines.append(",\n".join(fields_sql))
    sql_lines.append(");")
    sql_lines.append("")

sql_lines.append("-- Foreign Key Constraints")
for fk_sql in deferred_fks:
    sql_lines.append(fk_sql)

with open('technopath_oracle.sql', 'w') as f:
    f.write("\n".join(sql_lines))


# 2. Generate Python script for Data Dictionary
py_script_lines = []
py_script_lines.append("import sys")
py_script_lines.append("try:")
py_script_lines.append("    from docx import Document")
py_script_lines.append("    from docx.shared import Pt")
py_script_lines.append("    from docx.enum.text import WD_ALIGN_PARAGRAPH")
py_script_lines.append("    from docx.shared import RGBColor")
py_script_lines.append("except ImportError:")
py_script_lines.append("    print('Please install python-docx: pip install python-docx')")
py_script_lines.append("    sys.exit(1)")
py_script_lines.append("")
py_script_lines.append("schema = " + repr(schema))
py_script_lines.append("")
py_script_lines.append("def create_data_dictionary():")
py_script_lines.append("    document = Document()")
py_script_lines.append("    title = document.add_heading('Technopath Data Dictionary', 0)")
py_script_lines.append("    title.alignment = WD_ALIGN_PARAGRAPH.CENTER")
py_script_lines.append("")
py_script_lines.append("    for table_name, data in schema.items():")
py_script_lines.append("        if not table_name: continue")
py_script_lines.append("        document.add_heading(f'Table: {table_name} ({data[\"model_name\"]})', level=1)")
py_script_lines.append("        ")
py_script_lines.append("        # Create table: Column | Type | Null/Not Null | PK/FK | Value Config | Description")
py_script_lines.append("        table = document.add_table(rows=1, cols=6)")
py_script_lines.append("        table.style = 'Table Grid'")
py_script_lines.append("        hdr_cells = table.rows[0].cells")
py_script_lines.append("        headers = ['Column Name', 'Data Type', 'Null/Not Null', 'PK / FK', 'Value / Max Length', 'Description']")
py_script_lines.append("        for i, header in enumerate(headers):")
py_script_lines.append("            hdr_cells[i].text = header")
py_script_lines.append("            # Bold headers")
py_script_lines.append("            for run in hdr_cells[i].paragraphs[0].runs:")
py_script_lines.append("                run.font.bold = True")
py_script_lines.append("")
py_script_lines.append("        for field in data['fields']:")
py_script_lines.append("            if not field['name']: continue")
py_script_lines.append("            row_cells = table.add_row().cells")
py_script_lines.append("            row_cells[0].text = field['name']")
py_script_lines.append("            row_cells[1].text = field['type']")
py_script_lines.append("            row_cells[2].text = 'NULL' if field['null'] else 'NOT NULL'")
py_script_lines.append("            ")
py_script_lines.append("            pk_fk_text = []")
py_script_lines.append("            if field['pk']: pk_fk_text.append('PK')")
py_script_lines.append("            if field['fk']: pk_fk_text.append(f\"FK ({field['fk_table']})\")")
py_script_lines.append("            row_cells[3].text = ', '.join(pk_fk_text) if pk_fk_text else '-'")
py_script_lines.append("            ")
py_script_lines.append("            row_cells[4].text = str(field['max_length']) if field['max_length'] else '-'")
py_script_lines.append("            row_cells[5].text = field['help_text'] if field['help_text'] else field['verbose_name']")
py_script_lines.append("            ")
py_script_lines.append("        document.add_paragraph('---')")
py_script_lines.append("")
py_script_lines.append("    document.save('Data_Dictionary.docx')")
py_script_lines.append("    print('Data_Dictionary.docx successfully generated.')")
py_script_lines.append("")
py_script_lines.append("if __name__ == '__main__':")
py_script_lines.append("    create_data_dictionary()")

with open('generate_data_dictionary.py', 'w', encoding='utf-8') as f:
    f.write("\n".join(py_script_lines))

print("Created technopath_oracle.sql and generate_data_dictionary.py")
