import os
import sys
import django
import hashlib

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'technopath.settings')
django.setup()

from django.apps import apps

def get_oracle_type(internal_type, max_length):
    if internal_type in ['BigAutoField', 'AutoField', 'SmallAutoField']:
        return "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    elif internal_type == 'CharField':
        return f"VARCHAR2({max_length or 255})"
    elif internal_type == 'TextField':
        return "CLOB"
    elif internal_type in ['IntegerField', 'SmallIntegerField', 'BigIntegerField', 'PositiveIntegerField', 'PositiveSmallIntegerField']:
        return "NUMBER(10)"
    elif internal_type in ['DateTimeField', 'DateField', 'TimeField']:
        return "TIMESTAMP"
    elif internal_type == 'BooleanField':
        return "NUMBER(1)"
    elif internal_type == 'FloatField':
        return "FLOAT"
    elif internal_type in ['DecimalField']:
        return "NUMBER(10,2)"
    elif internal_type in ['ForeignKey', 'OneToOneField']:
        return "NUMBER"
    else:
        return "VARCHAR2(255)"

def get_fk_name(table_name, col_name):
    base = f"{table_name}_{col_name}_fk"
    if len(base) > 30:
        hash_str = hashlib.md5(base.encode()).hexdigest()[:4]
        return f"{base[:25]}_{hash_str}"
    return base

def generate_sql():
    models = apps.get_models(include_auto_created=True)
    
    tables_sql = []
    fks_sql = []
    
    for model in models:
        table_name = model._meta.db_table
        lines = []
        lines.append(f"CREATE TABLE {table_name} (")
        
        fields_def = []
        for f in model._meta.get_fields():
            if f.is_relation and f.many_to_many and not f.auto_created:
                continue
            
            if not hasattr(f, 'column') or not f.column:
                continue
                
            col_name = f.column
            internal_type = f.get_internal_type()
            max_length = getattr(f, 'max_length', None)
            
            db_type = get_oracle_type(internal_type, max_length)
            
            is_pk = getattr(f, 'primary_key', False)
            not_null = not getattr(f, 'null', False)
            
            line = f"    {col_name} {db_type}"
            if not is_pk and not_null:
                line += " NOT NULL"
            fields_def.append(line)
            
            if f.is_relation and f.many_to_one:
                # Need to handle case where related table is 'self' 
                related_model = f.related_model
                if related_model:
                    rel_table = related_model._meta.db_table
                    # Find related model's PK
                    rel_pk = related_model._meta.pk.column
                    constraint_name = get_fk_name(table_name, col_name)
                    fks_sql.append(f"ALTER TABLE {table_name} ADD CONSTRAINT {constraint_name} FOREIGN KEY ({col_name}) REFERENCES {rel_table}({rel_pk});")
                
        lines.append(",\n".join(fields_def))
        lines.append(");")
        tables_sql.append("\n".join(lines))
        
    tables_sql.append("""CREATE TABLE django_migrations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR2(255) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    applied TIMESTAMP NOT NULL
);""")
    
    with open('technopath_oracle.sql', 'w') as f:
        f.write("-- Technopath Oracle SQL Schema\n")
        f.write("-- Includes ALL 29 system tables (custom + django built-ins)\n\n")
        for t in tables_sql:
            f.write(t + "\n\n")
            
        f.write("-- Foreign Key Constraints\n")
        for fk in fks_sql:
            f.write(fk + "\n")

    print('technopath_oracle.sql regenerated successfully.')

if __name__ == '__main__':
    generate_sql()
