-- Technopath Oracle SQL Schema
-- Includes ALL 29 system tables (custom + django built-ins)

CREATE TABLE django_admin_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_time TIMESTAMP NOT NULL,
    user_id NUMBER NOT NULL,
    content_type_id NUMBER,
    object_id CLOB,
    object_repr VARCHAR2(200) NOT NULL,
    action_flag NUMBER(10) NOT NULL,
    change_message CLOB NOT NULL
);

CREATE TABLE auth_permission (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    content_type_id NUMBER NOT NULL,
    codename VARCHAR2(100) NOT NULL
);

CREATE TABLE auth_group_permissions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id NUMBER NOT NULL,
    permission_id NUMBER NOT NULL
);

CREATE TABLE auth_group (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(150) NOT NULL
);

CREATE TABLE django_content_type (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_label VARCHAR2(100) NOT NULL,
    model VARCHAR2(100) NOT NULL
);

CREATE TABLE django_session (
    session_key VARCHAR2(40),
    session_data CLOB NOT NULL,
    expire_date TIMESTAMP NOT NULL
);

CREATE TABLE admin_users_groups (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adminuser_id NUMBER NOT NULL,
    group_id NUMBER NOT NULL
);

CREATE TABLE admin_users_user_permissions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adminuser_id NUMBER NOT NULL,
    permission_id NUMBER NOT NULL
);

CREATE TABLE admin_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR2(128) NOT NULL,
    is_superuser NUMBER(1) NOT NULL,
    username VARCHAR2(150) NOT NULL,
    email VARCHAR2(254),
    display_name VARCHAR2(200),
    role VARCHAR2(20) NOT NULL,
    department VARCHAR2(50),
    department_label VARCHAR2(200),
    is_active NUMBER(1) NOT NULL,
    is_staff NUMBER(1) NOT NULL,
    login_attempts NUMBER(10) NOT NULL,
    locked_until TIMESTAMP,
    last_login TIMESTAMP,
    show_email_public NUMBER(1) NOT NULL,
    office_location VARCHAR2(100),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE facilities (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    code VARCHAR2(20) NOT NULL,
    description CLOB,
    facility_type VARCHAR2(20) NOT NULL,
    building_code VARCHAR2(20),
    department_id NUMBER,
    latitude FLOAT,
    longitude FLOAT,
    image_path VARCHAR2(500),
    map_svg_id VARCHAR2(100),
    total_floors NUMBER(10) NOT NULL,
    is_deleted NUMBER(1) NOT NULL,
    is_active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE rooms (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id NUMBER NOT NULL,
    name VARCHAR2(200) NOT NULL,
    code VARCHAR2(50) NOT NULL,
    room_number VARCHAR2(50),
    description CLOB,
    floor NUMBER(10) NOT NULL,
    map_svg_id VARCHAR2(100),
    room_type VARCHAR2(50) NOT NULL,
    capacity NUMBER(10) NOT NULL,
    is_office NUMBER(1) NOT NULL,
    is_crucial NUMBER(1) NOT NULL,
    search_count NUMBER(10) NOT NULL,
    course_code VARCHAR2(20),
    course_color VARCHAR2(7),
    is_deleted NUMBER(1) NOT NULL,
    is_active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE navigation_nodes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    node_type VARCHAR2(20) NOT NULL,
    facility_id NUMBER,
    room_id NUMBER,
    map_svg_id VARCHAR2(100),
    x FLOAT NOT NULL,
    y FLOAT NOT NULL,
    floor NUMBER(10) NOT NULL,
    is_deleted NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE navigation_edges (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_node_id NUMBER NOT NULL,
    to_node_id NUMBER NOT NULL,
    distance NUMBER(10) NOT NULL,
    is_bidirectional NUMBER(1) NOT NULL,
    is_deleted NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE faq_entries (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question CLOB NOT NULL,
    answer CLOB NOT NULL,
    category VARCHAR2(50) NOT NULL,
    keywords CLOB NOT NULL,
    usage_count NUMBER(10) NOT NULL,
    is_deleted NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE ai_chat_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_query CLOB NOT NULL,
    ai_response CLOB,
    mode VARCHAR2(10) NOT NULL,
    response_time_ms NUMBER(10),
    is_successful NUMBER(1) NOT NULL,
    error_message CLOB,
    faq_entry_id NUMBER,
    session_id VARCHAR2(100),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE notifications (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    message CLOB NOT NULL,
    type VARCHAR2(30) NOT NULL,
    source_label VARCHAR2(200) NOT NULL,
    source_color VARCHAR2(20) NOT NULL,
    announcement_id NUMBER,
    priority NUMBER(10) NOT NULL,
    expires_at TIMESTAMP,
    created_by_id NUMBER,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE notification_read_status (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    notification_id NUMBER NOT NULL,
    read_at TIMESTAMP NOT NULL
);

CREATE TABLE feedback (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating NUMBER(10),
    comment CLOB,
    category VARCHAR2(30) NOT NULL,
    facility_id NUMBER,
    room_id NUMBER,
    is_anonymous NUMBER(1) NOT NULL,
    location VARCHAR2(200),
    is_flagged NUMBER(1) NOT NULL,
    flag_reason CLOB,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE departments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    code VARCHAR2(20) NOT NULL,
    description CLOB,
    head_user_id NUMBER,
    is_active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE map_markers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id NUMBER,
    room_id NUMBER,
    name VARCHAR2(200) NOT NULL,
    x_position FLOAT NOT NULL,
    y_position FLOAT NOT NULL,
    marker_type VARCHAR2(20) NOT NULL,
    icon_name VARCHAR2(100) NOT NULL,
    color_hex VARCHAR2(7) NOT NULL,
    is_active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE map_labels (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label_text VARCHAR2(200) NOT NULL,
    x_position FLOAT NOT NULL,
    y_position FLOAT NOT NULL,
    font_size NUMBER(10) NOT NULL,
    color_hex VARCHAR2(7) NOT NULL,
    rotation FLOAT NOT NULL,
    is_active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE notification_types (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description CLOB,
    icon_name VARCHAR2(100) NOT NULL,
    color_hex VARCHAR2(7) NOT NULL,
    is_active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE notification_preferences (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    notification_type_id NUMBER NOT NULL,
    is_enabled NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE admin_audit_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER,
    action VARCHAR2(20) NOT NULL,
    entity_type VARCHAR2(50),
    entity_id NUMBER(10),
    entity_label VARCHAR2(200),
    old_value_json CLOB,
    new_value_json CLOB,
    ip_address VARCHAR2(50),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE search_history (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    query VARCHAR2(500) NOT NULL,
    results_count NUMBER(10) NOT NULL,
    was_clicked NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE app_config (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR2(100) NOT NULL,
    config_value CLOB NOT NULL,
    description CLOB,
    updated_by_id NUMBER,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE announcements (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    content CLOB NOT NULL,
    created_by_id NUMBER,
    source_label VARCHAR2(200) NOT NULL,
    source_color VARCHAR2(20) NOT NULL,
    scope VARCHAR2(20) NOT NULL,
    target_department VARCHAR2(50),
    status VARCHAR2(20) NOT NULL,
    requires_approval NUMBER(1) NOT NULL,
    approved_by_id NUMBER,
    rejected_by_id NUMBER,
    rejection_note CLOB,
    approved_at TIMESTAMP,
    archived_by_id NUMBER,
    archived_at TIMESTAMP,
    is_deleted NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE django_migrations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR2(255) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    applied TIMESTAMP NOT NULL
);

-- Foreign Key Constraints
ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_user_id_fk FOREIGN KEY (user_id) REFERENCES admin_users(id);
ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_content__b0b4 FOREIGN KEY (content_type_id) REFERENCES django_content_type(id);
ALTER TABLE auth_permission ADD CONSTRAINT auth_permission_content_t_3558 FOREIGN KEY (content_type_id) REFERENCES django_content_type(id);
ALTER TABLE auth_group_permissions ADD CONSTRAINT auth_group_permissions_gr_4fa8 FOREIGN KEY (group_id) REFERENCES auth_group(id);
ALTER TABLE auth_group_permissions ADD CONSTRAINT auth_group_permissions_pe_3dae FOREIGN KEY (permission_id) REFERENCES auth_permission(id);
ALTER TABLE admin_users_groups ADD CONSTRAINT admin_users_groups_adminu_b6b6 FOREIGN KEY (adminuser_id) REFERENCES admin_users(id);
ALTER TABLE admin_users_groups ADD CONSTRAINT admin_users_groups_group_id_fk FOREIGN KEY (group_id) REFERENCES auth_group(id);
ALTER TABLE admin_users_user_permissions ADD CONSTRAINT admin_users_user_permissi_1b19 FOREIGN KEY (adminuser_id) REFERENCES admin_users(id);
ALTER TABLE admin_users_user_permissions ADD CONSTRAINT admin_users_user_permissi_97f9 FOREIGN KEY (permission_id) REFERENCES auth_permission(id);
ALTER TABLE facilities ADD CONSTRAINT facilities_department_id_fk FOREIGN KEY (department_id) REFERENCES departments(id);
ALTER TABLE rooms ADD CONSTRAINT rooms_facility_id_fk FOREIGN KEY (facility_id) REFERENCES facilities(id);
ALTER TABLE navigation_nodes ADD CONSTRAINT navigation_nodes_facility_86d9 FOREIGN KEY (facility_id) REFERENCES facilities(id);
ALTER TABLE navigation_nodes ADD CONSTRAINT navigation_nodes_room_id_fk FOREIGN KEY (room_id) REFERENCES rooms(id);
ALTER TABLE navigation_edges ADD CONSTRAINT navigation_edges_from_nod_5d08 FOREIGN KEY (from_node_id) REFERENCES navigation_nodes(id);
ALTER TABLE navigation_edges ADD CONSTRAINT navigation_edges_to_node_id_fk FOREIGN KEY (to_node_id) REFERENCES navigation_nodes(id);
ALTER TABLE ai_chat_logs ADD CONSTRAINT ai_chat_logs_faq_entry_id_fk FOREIGN KEY (faq_entry_id) REFERENCES faq_entries(id);
ALTER TABLE notifications ADD CONSTRAINT notifications_announcemen_85ce FOREIGN KEY (announcement_id) REFERENCES announcements(id);
ALTER TABLE notifications ADD CONSTRAINT notifications_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES admin_users(id);
ALTER TABLE notification_read_status ADD CONSTRAINT notification_read_status__2411 FOREIGN KEY (user_id) REFERENCES admin_users(id);
ALTER TABLE notification_read_status ADD CONSTRAINT notification_read_status__3747 FOREIGN KEY (notification_id) REFERENCES notifications(id);
ALTER TABLE feedback ADD CONSTRAINT feedback_facility_id_fk FOREIGN KEY (facility_id) REFERENCES facilities(id);
ALTER TABLE feedback ADD CONSTRAINT feedback_room_id_fk FOREIGN KEY (room_id) REFERENCES rooms(id);
ALTER TABLE departments ADD CONSTRAINT departments_head_user_id_fk FOREIGN KEY (head_user_id) REFERENCES admin_users(id);
ALTER TABLE map_markers ADD CONSTRAINT map_markers_facility_id_fk FOREIGN KEY (facility_id) REFERENCES facilities(id);
ALTER TABLE map_markers ADD CONSTRAINT map_markers_room_id_fk FOREIGN KEY (room_id) REFERENCES rooms(id);
ALTER TABLE notification_preferences ADD CONSTRAINT notification_preferences__c7a8 FOREIGN KEY (user_id) REFERENCES admin_users(id);
ALTER TABLE notification_preferences ADD CONSTRAINT notification_preferences__2d0e FOREIGN KEY (notification_type_id) REFERENCES notification_types(id);
ALTER TABLE admin_audit_log ADD CONSTRAINT admin_audit_log_admin_id_fk FOREIGN KEY (admin_id) REFERENCES admin_users(id);
ALTER TABLE search_history ADD CONSTRAINT search_history_user_id_fk FOREIGN KEY (user_id) REFERENCES admin_users(id);
ALTER TABLE app_config ADD CONSTRAINT app_config_updated_by_id_fk FOREIGN KEY (updated_by_id) REFERENCES admin_users(id);
ALTER TABLE announcements ADD CONSTRAINT announcements_created_by_id_fk FOREIGN KEY (created_by_id) REFERENCES admin_users(id);
ALTER TABLE announcements ADD CONSTRAINT announcements_approved_by_bf18 FOREIGN KEY (approved_by_id) REFERENCES admin_users(id);
ALTER TABLE announcements ADD CONSTRAINT announcements_rejected_by_897d FOREIGN KEY (rejected_by_id) REFERENCES admin_users(id);
ALTER TABLE announcements ADD CONSTRAINT announcements_archived_by_eb22 FOREIGN KEY (archived_by_id) REFERENCES admin_users(id);
