# Generated by Django 6.0.3 on 2026-03-30 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('location', 'Location'), ('schedule', 'Schedule'), ('academic', 'Academic'), ('services', 'Services'), ('general', 'General')], default='general', max_length=50)),
                ('keywords', models.TextField(blank=True, default='', help_text='Comma-separated keywords for offline matching')),
                ('usage_count', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'faq_entries',
            },
        ),
        migrations.CreateModel(
            name='AIChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField()),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('online', 'Online AI'), ('offline', 'Offline FAQ Fallback')], max_length=10)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faq_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.faqentry')),
            ],
            options={
                'db_table': 'ai_chat_logs',
            },
        ),
    ]
