# Generated by Django 6.0.3 on 2026-05-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_faqsuggestion_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('response_text', models.TextField()),
                ('intent_detected', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down')], max_length=20)),
                ('rating_note', models.TextField(blank=True, help_text='Optional user feedback', null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='Example user query')),
                ('intent_label', models.CharField(choices=[('library_hours', 'Library Hours'), ('registrar', 'Registrar Office'), ('dean_office', 'Dean Office'), ('room_location', 'Room/Location'), ('schedule', 'Schedule/Time'), ('admission', 'Admission/Enrollment'), ('scholarship', 'Scholarship/Financial'), ('it_support', 'IT Support'), ('safety_security', 'Safety/Security'), ('general', 'General')], max_length=50)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('faq', 'From FAQ'), ('rating', 'From User Rating')], default='manual', max_length=50)),
                ('used_for_training', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'training_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
