# Generated by Django 6.0.3 on 2026-03-30 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('floor', models.IntegerField(default=1)),
                ('map_svg_id', models.CharField(blank=True, help_text='SVG element ID e.g. RST-F1-CL1', max_length=100, null=True)),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('office', 'Office'), ('lab', 'Laboratory'), ('facility', 'Facility'), ('staircase', 'Staircase'), ('restroom', 'Restroom'), ('other', 'Other')], default='classroom', max_length=50)),
                ('capacity', models.IntegerField(default=30)),
                ('is_office', models.BooleanField(default=False)),
                ('is_crucial', models.BooleanField(default=False)),
                ('search_count', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='facilities.facility')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
