# Generated by Django 6.0.3 on 2026-03-30 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('node_type', models.CharField(choices=[('room', 'Room'), ('facility', 'Facility'), ('waypoint', 'Waypoint'), ('entrance', 'Entrance'), ('staircase', 'Staircase'), ('elevator', 'Elevator'), ('junction', 'Junction')], max_length=20)),
                ('map_svg_id', models.CharField(blank=True, max_length=100, null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('floor', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.facility')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room')),
            ],
            options={
                'db_table': 'navigation_nodes',
            },
        ),
        migrations.CreateModel(
            name='NavigationEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('is_bidirectional', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='navigation.navigationnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='navigation.navigationnode')),
            ],
            options={
                'db_table': 'navigation_edges',
            },
        ),
    ]
